name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu runner for the CI

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK (Java 11 or the version you are using)
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'

      # Step 3: Build the application using Maven
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # Step 4: Run tests (you can remove this step if you don't want to run tests)
      - name: Run tests
        run: mvn test
